added HW requirements
mate-academy/hibernate-inheritance-example pull request #1
Opened 2020-09-17 05:31 UTC by boroda4436

2020-09-17 12:59 UTC, Sofasmile commented on README.md
> +Add the implementation of `Implicit strategy (Hibernate only)` inheritance strategy.
ми хочемо щоб вони і це імплементовували? Як на мене то 3 основних - достатньо
ну і можна ще Mapped Superclass залишити

2020-09-17 13:15 UTC, KseniiaMakarova commented on README.md
> +1. There are classes: Animal, Cat and Dog. Both Cat and Dog extends Animal.
```suggestion
1. There are classes: Animal, Cat and Dog. Both Cat and Dog extend Animal. 
```

2020-09-17 13:15 UTC, KseniiaMakarova commented on README.md
> +1. There are classes: Machine, Car and Truck. Both Car and Truck extends Machine.
```suggestion
1. There are classes: Machine, Car and Truck. Both Car and Truck extend Machine. 
```

2020-09-17 13:15 UTC, KseniiaMakarova commented on README.md
> +1. There are classes: Person, Coach and Mentor. Both Coach and Mentor extends Person.
```suggestion
1. There are classes: Person, Coach and Mentor. Both Coach and Mentor extend Person. 
```

2020-09-17 13:15 UTC, KseniiaMakarova commented on README.md
> +1. There are classes: Character, Bowman and Farmer. Both Bowman and Farmer extends Character.
```suggestion
1. There are classes: Character, Bowman and Farmer. Both Bowman and Farmer extend Character. 
```

2020-09-17 13:15 UTC, KseniiaMakarova commented on README.md
> +1. There are classes: Figure, Circle and Triangle. Both Circle and Triangle extends Figure.
```suggestion
1. There are classes: Figure, Circle and Triangle. Both Circle and Triangle extend Figure. 
```

2020-09-17 13:15 UTC, KseniiaMakarova commented on README.md
> +1. Select all cats and dogs where name starts with 'A'.
```suggestion
1. Select all cats and dogs whose name starts with 'A'.
```

2020-09-22 05:22 UTC, KseniiaMakarova requested changes

2020-09-22 05:22 UTC, KseniiaMakarova commented on README.md
> +1. Select all cars and trucks older than 4 days.
```suggestion
```

2020-09-25 09:56 UTC, dmytro-hryhoruk reviewed
I think we should add more information about dao methods and classess(one common, or for each entity e.g) base on our with @KseniiaMakarova  solutions

2020-09-25 09:56 UTC, dmytro-hryhoruk commented on README.md
> +### Implement all required methods in DAOs
it seems to me that we had tasks here?

2020-09-25 10:00 UTC, dmytro-hryhoruk approved these changes

2020-09-25 10:26 UTC, merged