Hibernate_Inheritance_HW
mate-academy/hibernate-inheritance-example pull request #163
Opened 2022-03-10 20:16 UTC by AlexPravda1

- Inheritance annotations added to models
- Dao level implemeneted
- Prepared Query used

2022-03-11 12:27 UTC, MaliukDaria requested changes

2022-03-11 12:27 UTC, MaliukDaria commented on src/main/java/core/basesyntax/dao/animal/AnimalDaoImpl.java
> +                    .collect(Collectors.toList());
It's bad practice to get all animals from db and than filter them, let's create a query that will get the necessary records from the database

2022-03-11 12:27 UTC, MaliukDaria commented on src/main/java/core/basesyntax/dao/figure/FigureDaoImpl.java
> +                            + clazz.getName().substring(clazz.getName().lastIndexOf(".") + 1)
maybe it's better to use clazz.getName().getSimpleName() here?

2022-03-14 16:18 UTC, KseniiaMakarova requested changes

2022-03-14 16:18 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/dao/ma/CoachDaoImpl.java
> +                    .setParameter("exp", years)
```suggestion
                    .setParameter("experience", years)
```

2022-03-14 16:18 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/dao/ma/CoachDaoImpl.java
> +            throw new RuntimeException("Can't find Coach Person with exp more years than: "
same - don't use shortenings

2022-03-14 16:18 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/model/zoo/Animal.java
> +@Inheritance (strategy = InheritanceType.TABLE_PER_CLASS)
should we use TABLE_PER_CLASS here?

2024-04-19 10:05 UTC, closed without merging